import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroidaöv.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Aszteroidaov {
	private List<Robot> robotok = new ArrayList<>();
	private List<Telepes> telepesek = new ArrayList<>();
	private List<Ufo> ufok = new ArrayList<>();
	
	public void DoNapvihar() {
	}
	
	public void MinuszAszteroida(Aszteroida a) {
	}
	
	public void DoNapkozel() {
	}
}
