import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroida.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Aszteroida extends Szomszed {
	private int kopenyVastagsag;
	private boolean napkozel;
	private Entitas entitasok;
	private List<Szomszed> szomszedok = new ArrayList<>();
	private Nyersanyag belsoAnyag;
	
	List<Szomszed> getSzomszedok(){
		return szomszedok;
	}
	
	public Nyersanyag AnyagKinyeres() {
	}
	
	public void Ledob(Entitas a) {
	}
	
	public void Befogad(Entitas a) {
	}
	
	public void Napvihar() {
	}
	
	public void SzomszedTorol(Szomszed a) {
	}
	
	public void BazisEpit() {
	}
	
	public void KeregCsokken() {
	}
	
	public void Robban() {
	}
	
	public szomszéd SzomszedotAd() {
	}
	
	public void Raktaroz(Nyersanyag a, Telepes t) {
	}
	
	public void AnyagTorol() {
	}
	
	public void StartNapvihar() {
	}	
	
	public void KapuBefogad(Teleportkapu k) {
	}
}
