//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroida.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Aszteroida extends Szomszed {
	private int kopenyVastagsag;
	private boolean napkozel;
	private Aszteroidaov aszteroidak;
	private Entitas entitasok;
	private Szomszed szomszedok;
	public Nyersanyag AnyagKinyeres() {
	}
	
	public void Ledob(Entitas a) {
	}
	
	public void Befogad(Entitas a) {
	}
	
	public void Napvihar() {
	}
	
	public void SzomszedTorol(Szomszed a) {
	}
	
	public void BazisEpit() {
	}
	
	public void KeregCsokken() {
	}
	
	public void Robban() {
	}
	
	public szomszéd SzomszedotAd() {
	}
	
	public void Raktaroz(Nyersanyag a) {
	}
	
	public void AnyagTorol() {
	}
	
	public void StartNapvihar() {
	}
	
	public void KapuBefogad(Teleportkapu k) {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitas a) {
	}
	
	public void Napvihar() {
	}
	
	public void KapuBefogad(Teleportkapu k) {
	}
}
