//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entitás.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public abstract class Entitás {
	private Aszteroida aszteroida;
	public abstract void Furas();
	public abstract void Halal();
	public abstract void Felrobban();
	public abstract void Lep();
}
