//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Intelligencia.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Intelligencia {
	public void RandomMozgas(Szomszéd a) {
	}
}
