//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Játék.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Játék {
	private Aszteroidaöv jatekter;
	public void Start() {
	}
	
	public void Kor() {
	}
	
	public void Vege(boolean a) {
	}
}
