//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nyersanyag.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//

public abstract class Nyersanyag {
	
	public abstract void Betolt(Telepes a);
	public abstract void Napkozel(Aszteroida a);
	public abstract boolean Kompatibilis(Nyersanyag ny);
}
