import java.io.Serializable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nyersanyag.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//

public abstract class Nyersanyag implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4128594175231573747L;
	protected String ID;
	
	public abstract void Betolt(Telepes a);
	public abstract void Napkozel(Aszteroida a);
	public abstract boolean Kompatibilis(Nyersanyag ny);
	
	public String getID() {
		return ID;
	}
	
	public void setID(String id) {
		ID = id;
	}
}
