//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Robot extends Entitas implements Intelligencia {
	private Aszteroidaov robotok;
	public void RandomMozgas(Szomszed a) {
	}
	
	public void Felrobban() {
	}
	
	public void Halal() {
	}
	
	public void Lep() {
	}
	
	public void Furas() {
	}
	
	public void Furas() {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
}
