//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Robot extends Entitas implements Intelligencia {
	
	public void RandomMozgas() {
	}
	
	public void Felrobban() {
	}
	
	public void Halal() {
	}
	
	public void Lep() {
	}
	
	public void Furas() {
	}
	
	public void BazisEpit() {
		
	}
}
