//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Robot extends Entitas implements Intelligencia {
	private static int count=0;
	private String ID;
	Robot(){
		super();
		ID="r0"+count++;
	}
	
	public void RandomMozgas() {
		Szomszed b = aszteroida.SzomszedotAd();
		aszteroida.Ledob(this);
		b.Befogad(this);
	}
	
	public void Felrobban() {
		RandomMozgas();
	}
	
	public void Halal() {
	}
	
	public void Lep() {
		RandomMozgas();
	}
	
	public void Furas() {
		if(aszteroida.getKopenyVastagsag() > 0)
			aszteroida.KeregCsokken();
	}
	
	public void BazisEpit() {
		
	}
}
