import java.io.Serializable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szomszéd.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public abstract class Szomszed implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -7002053200057188774L;
	private String ID;

	public abstract void Robban();
	
	public abstract void Befogad(Entitas a);
	
	public abstract void Napvihar();
	
	public abstract void KapuBefogad(Teleportkapu k);
	
	public  abstract void MegKergul();
	
	public  abstract void SzomszedTorol(Szomszed a);


	public String getID() {
		return ID;
	}

	
	
}
