//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szomszéd.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public abstract class Szomszéd {
	public abstract void Robban();
	public abstract void Befogad(Entitás a);
	public abstract void Napvihar();
	public abstract void KapuBefogad(Teleportkapu k);
}
