import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleportkapu.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Teleportkapu extends Szomszed implements Intelligencia{
	/**
	 * 
	 */
	private static final long serialVersionUID = 4398516018408113362L;
	private Aszteroida aszteroida;
	private boolean megkergult;
	private Teleportkapu parja;
	
	public Teleportkapu() {
		aszteroida=null;
		megkergult=false;
		parja=null;
	}
	
	public Teleportkapu getParja() {
		return parja;
	}
	
	public void setParja(Teleportkapu par) {
		parja=par;
	}
	
	public Aszteroida getAszter() {
		return aszteroida;
	}
	
	public void setAszter(Aszteroida a) {
		aszteroida=a;
	}
	
	public Aszteroida ParHelye() {
		return this.getParja().getAszter();
	}
	
	public void Robban() {
		aszteroida.SzomszedTorol(this);
		parja.setParja(parja);
	}
	
	public void Befogad(Entitas a) {
		a.SetAszteroida(this.ParHelye());
		Aszteroida x= new Aszteroida();
		x= this.ParHelye();
		x.Befogad(a);
	}
	
	public void Napvihar() {
		megkergult=true;
	}
	
	public void RandomMozgas() {   //kivettem a paramétert mert szerintem nem hasznos
		Szomszed cel= aszteroida.SzomszedotAd();
		aszteroida.SzomszedTorol(this);
		cel.KapuBefogad(this);
		          
	}
	
	public void KapuBefogad(Teleportkapu k) {
		
		Aszteroida a= this.ParHelye();
		a.KapuBefogad(k);
	}
	
	
}
