//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleportkapu.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Teleportkapu extends Szomszed implements Intelligencia {
	private 
	Aszteroida aszteroida;
	private boolean megkergult;
	private Teleportkapu parja;
	
	public Teleportkapu getParja() {
		return parja;
	}
	
	public void setParja(Teleportkapu par) {
		parja=par;
	}
	
	public Aszteroida getAszter() {
		return aszteroida;
	}
	
	public void setAszter(Aszteroida a) {
		aszteroida=a;
	}
	
	public Aszteroida ParHelye() {
		return this.getParja().getAszter();
	}
	
	public void Robban() {
		
	}
	
	public void Befogad(Entitas a) {
	}
	
	public void Napvihar() {
	}
	
	public void RandomMozgas(Szomszed a) {
	}
	
	public void KapuBefogad(Teleportkapu k) {
	}
	
	
}
