//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleportkapu.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Teleportkapu extends Szomszéd implements Intelligencia {
	private boolean megkergult;
	private Teleportkapu parja;
	private Telepes kapuk;
	private Aszteroidaöv kapuk;
	public Aszteroida ParHelye() {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitás a) {
	}
	
	public void Napvihar() {
	}
	
	public void RandomMozgas(Szomszéd a) {
	}
	
	public void KapuBefogad(Teleportkapu k) {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitás a) {
	}
	
	public void Napvihar() {
	}
	
	public void KapuBefogad(Teleportkapu k) {
	}
}
