//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Telepes.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Telepes extends Entitas {
	private Aszteroidaov telepesek;
	public void Felrobban() {
	}
	
	public void Mozgas(Szomszed a) {
	}
	
	public void Banyaszat() {
	}
	
	public void Visszatolt() {
	}
	
	public Robot RobotEpit() {
	}
	
	public void KapuEpit() {
	}
	
	public void KapuLerak() {
	}
	
	public void BazisEpit() {
	}
	
	public void Halal() {
	}
	
	public void Lep() {
	}
	
	public void Furas() {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
}
