//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ufó.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Ufó extends Entitás implements Intelligencia {
	private Aszteroidaöv ufok;
	public void RandomMozgas(Szomszéd a) {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
	
	public void Banyaszat() {
	}
	
	public void Furas() {
	}
	
	public void Furas() {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
}
