//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Urán.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Uran extends Nyersanyag {
	private int expozicio;
	
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel(Aszteroida a) {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
	}
}
