import java.util.ArrayList;
import java.util.List;

import szkeleton.game.Main;
import szkeleton.game.Nyersanyag;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Útmutató.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Utmutato {
	private List<Nyersanyag> hozzavalok = new List<Nyersanyag>() ;
	private List<Nyersanyag> megvanLista = new List<Nyersanyag>();
	
	//ezt biztos hogy nem így kell, de akkor paraméterben listát adjunk át?
	Utmutato(List<Nyersanyag> kellenek){
		hozzavalok = new ArrayList<Nyersanyag>();
		for(Nyersanyag n : kellenek) {
			hozzavalok.add(n);
		}
		megvanLista = new ArrayList<Nyersanyag>();
	}
	public boolean MindMegvan(Nyersanyag ny) {
		boolean answer;
		for(Nyersanyag n : hozzavalok) {
			answer = n.Kompatibilis(ny);
			if(answer) {
				return true;
			}
		}
		return false;
	}
}
