//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vas.java
//  @ Date : 2021. 04. 08.
//  @ Author : 
//
//




public class Vas extends Nyersanyag {
	
	/**
	 * A szerializálást elõsegítõ ID
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * az id egyediségét biztosító számláló
	 */
	private static int count=1;
	/**
	 * A nyersanyag azonosítására szolgáló ID
	 */
	//private String ID;
	
	/**
	 * A Vas osztály konstruktora.
	 */
	public Vas() {
		super();
		ID="v0"+count++;
	}
	
	/**
	 * A Nyersanyag betöltését végzi a telepes inventoryjába.
	 * @param A Telepes, aki bányászik.
	 */
	public void Betolt(Telepes a) {
		a.AddNyersanyag(this);
	}
	
	/**
	 * A nyersanyag napközelbe kerülését végzõ függvény.
	 * @param Az aszteroida, amiben a nyersanyag van.
	 */
	public void Napkozel(Aszteroida a) {
	}
	
	/**
	 * A Nyersanyagok összehasonlítását végzõ függvény.
	 * @param A Nyersanyag, amivel össze kell hasonlítania önmagát.
	 * @return Egy logikai változó, ami megmondja, hogy ugyanolyan fajátjúak-e az összehasonlított Nyersanyagok.
	 */
	public boolean Kompatibilis(Nyersanyag ny) {
		return ny instanceof Vas;
	}
	
	/**
	 * Amennyiben van expozicioja a nyersanyagnak, akkor azt megnöveli.
	 * @param A szám, amivel növelje az expoziciot.
	 */
	public void setExp(int i) {
		
	}
	
	public String toString() {
		return "Vas";
	}

	@Override
	protected int getExp() {
		// TODO Auto-generated method stub
		return 0;
	}
}
